export const EVENTS = [
  {id:'INJ-01', day:1,  overnight:false, type:'time',
    desc:'Monitoring logs flag unusual 4.3GB export from NovaCare integration at 06:22.',
    effects:[{pool:'INTELLIGENCE_QUALITY',delta:2}], condition:null},
  {id:'INJ-02', day:1,  overnight:false, type:'time',
    desc:'Claire Ashworth emails CISO at 09:47. 48-hour publication deadline. 40-record sample attached.',
    effects:[], condition:null},
  {id:'INJ-03', day:1,  overnight:false, type:'time',
    desc:'NovaCare security contact unresponsive — acknowledgement email only. Third-party trust signal negative.',
    effects:[{pool:'THIRD_PARTY_TRUST',delta:-5}], condition:null},
  {id:'INJ-04', day:2,  overnight:false, type:'time',
    desc:'CISO team confirms: sample records are authentic Meridian data. Decision gate G2 activated.',
    effects:[{pool:'INTELLIGENCE_QUALITY',delta:8}], condition:null},
  {id:'INJ-05', day:3,  overnight:false, type:'time',
    desc:'NovaCare issues formal denial of breach on their infrastructure at 14:30.',
    effects:[{pool:'THIRD_PARTY_TRUST',delta:-8}], condition:null},
  {id:'INJ-06', day:4,  overnight:false, type:'time',
    desc:'Board Chair Lisa Park calls CEO asking for briefing. Legal Fault Line card activated.',
    effects:[], condition:null},
  {id:'INJ-07', day:5,  overnight:false, type:'conditional',
    desc:'Forensics firm delivers interim brief (if G3 = A or B engaged). Intelligence quality improves.',
    effects:[], condition:'G3_AB'},
  {id:'INJ-08', day:7,  overnight:true,  type:'overnight',
    desc:'MORNING EVENT — Ashworth sends reminder: "Publishing in 24h per my earlier commitment."',
    effects:[], condition:null},
  {id:'INJ-09', day:7,  overnight:false, type:'time',
    desc:'ACT 1 CLOSE — Session 2 live checkpoint. Team regroups. Capacity refresh.',
    effects:[{pool:'CAPACITY',delta:10}], condition:null},
  {id:'INJ-10', day:8,  overnight:true,  type:'overnight',
    desc:'MORNING EVENT — Claire Ashworth\'s Substack post goes live. Cross-posted to The Guardian AU at 09:30. G6 activated.',
    effects:[{pool:'REPUTATION',delta:-12},{pool:'COMMS.MESSAGE_CONTROL',delta:-15}], condition:null},
  {id:'INJ-11', day:8,  overnight:false, type:'conditional',
    desc:'Three major outlets pick up the story (if G6 = B or C response). Additional reputation damage.',
    effects:[{pool:'REPUTATION',delta:-5},{pool:'COMMS.MEDIA_RELATIONSHIPS',delta:-3}], condition:'G6_BC'},
  {id:'INJ-12', day:9,  overnight:true,  type:'overnight',
    desc:'MORNING EVENT — Dr. Obi reads article on the train; realises her data is in the sample (only fires if G5 = C).',
    effects:[{pool:'DR_OBI_TRAJECTORY',delta:-20}], condition:'G5_C'},
  {id:'INJ-13', day:10, overnight:false, type:'state',
    desc:'If REPUTATION below 0: patient advocacy group issues demand statement.',
    effects:[{pool:'PATIENT_CONFIDENCE',delta:-8},{pool:'COMMS.MESSAGE_CONTROL',delta:-5}], condition:'REP_NEG'},
  {id:'INJ-14', day:10, overnight:false, type:'time',
    desc:'Attribution Board minigame fires. Decision gate G7 activated. Forensics report supports aggregator attribution.',
    effects:[], condition:null},
  {id:'INJ-15', day:11, overnight:false, type:'time',
    desc:'Emergency board meeting. Budget decision required. Decision gate G8 activated.',
    effects:[], condition:null},
  {id:'INJ-16', day:12, overnight:false, type:'conditional',
    desc:'Dr. Obi\'s response materialises based on G5 choice: resignation, litigation, or cooperation.',
    effects:[], condition:null},
  {id:'INJ-17', day:13, overnight:false, type:'time',
    desc:'OAIC formal contact at 10:00. Notification Clock minigame fires. Decision gate G9 activated.',
    effects:[], condition:null},
  {id:'INJ-18', day:13, overnight:false, type:'state',
    desc:'If G6 = C (rebuttal) or RESEARCHER_GOODWILL < 20: second researcher contacts media with additional findings.',
    effects:[{pool:'REPUTATION',delta:-10},{pool:'INTELLIGENCE_QUALITY',delta:-5}], condition:'G6C_or_RG20'},
  {id:'INJ-19', day:14, overnight:false, type:'state',
    desc:'If PATIENT_CONFIDENCE < 40: law firm announces investigation into potential class action.',
    effects:[{pool:'LEGAL.LEGAL_EXPOSURE',delta:15}], condition:'PC_LOW'},
  {id:'INJ-20', day:14, overnight:false, type:'time',
    desc:'Decision gate G10 activated. Strategic posture decision required.',
    effects:[], condition:null},
  {id:'INJ-21', day:15, overnight:false, type:'time',
    desc:'ACT 2 CLOSE — Session 4 live checkpoint. State shape becomes clear. Ending trajectory visible. Capacity reset.',
    effects:[{pool:'CAPACITY',delta:5}], condition:null},
  {id:'INJ-22', day:16, overnight:false, type:'time',
    desc:'OAIC preliminary findings delivered. Regulatory standing shift per G9 state.',
    effects:[], condition:null},
  {id:'INJ-23', day:17, overnight:false, type:'time',
    desc:'Dr. Obi trajectory resolves. Decision gate G11 activated.',
    effects:[], condition:null},
  {id:'INJ-24', day:18, overnight:false, type:'time',
    desc:'Board accountability session. CEO position formally addressed. Decision gate G12 activated.',
    effects:[], condition:null},
  {id:'INJ-25', day:19, overnight:false, type:'time',
    desc:'ACT 3 — Session 5 live. Final public narrative decided. Decision gate G13 activated. Narrative branches lock.',
    effects:[], condition:null},
  {id:'INJ-26', day:20, overnight:false, type:'time',
    desc:'RESOLUTION — Ending-specific events fire. Press coverage, regulator statement, stakeholder responses.',
    effects:[], condition:null},
  {id:'INJ-27', day:21, overnight:false, type:'time',
    desc:'DEBRIEF — Session 6 (90 min). State log released. Replay enabled. Scenario ends.',
    effects:[], condition:null},
];

export function evaluateEventCondition(condition, state, decisions) {
  if (!condition) return true;
  switch (condition) {
    case 'G3_AB':       return decisions['G3'] === 'A' || decisions['G3'] === 'B';
    case 'G6_BC':       return decisions['G6'] === 'B' || decisions['G6'] === 'C';
    case 'G5_C':        return decisions['G5'] === 'C';
    case 'REP_NEG':     return state['REPUTATION'] < 0;
    case 'G6C_or_RG20': return decisions['G6'] === 'C' || state['RESEARCHER_GOODWILL'] < 20;
    case 'PC_LOW':      return state['PATIENT_CONFIDENCE'] < 40;
    default:            return true;
  }
}
